{
 "title": "Locust Testruns",
 "tags": [ "load_test" ],
 "time": { "from": "2022-03-26T10:57:14.347Z", "to": "2022-03-30T01:56:00.080Z" },
 "templating": {
  "list": [
   {
    "name": "testplan",
    "query": "SELECT DISTINCT testplan FROM testrun WHERE $__timeFilter(id)"
   },
   {
    "name": "username",
    "query": "SELECT DISTINCT username FROM testrun WHERE $__timeFilter(id)"
   },
   {
    "name": "env",
    "query": "SELECT DISTINCT env FROM testrun WHERE $__timeFilter(id)"
   },
   { "name": "min_users", "query": "0" },
   { "name": "max_users", "query": "9999" }
  ]
 },
 "panels": [
  {
   "title": "Testrun",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \n id,\n testplan, \n num_clients, \n round(rps_avg, 1) as rps_avg,\n nullif(rps, 0) as rps_target,\n round(resp_time_avg, 1) as resp_time,\n fail_ratio,\n requests, \n date_trunc('second', end_time - id) AS \"run time\",\n end_time AS \"end time\",\n env,\n description,\n username,\n gitrepo,\n changeset_guid,\n round(date_part('epoch', id)*1000) AS start_time_epoch, \n CASE WHEN end_time IS NULL \n THEN round((date_part('epoch', id)*1000)+300000) -- make a useable link even when there is no end time\n ELSE round(date_part('epoch', end_time)*1000) \n END AS end_time_epoch,\n exit_code,\n arguments\nFROM testrun\nWHERE $__timeFilter(id) and \n testplan = ANY(ARRAY[$testplan]::varchar[]) and -- couldnt use a simple testplan IN ($testplan), because postgres fails if $testplan is empty\n username = ANY(ARRAY[$username]::varchar[]) and\n env = ANY(ARRAY[$env]::varchar[]) and \n num_clients >= $min_users and \n num_clients <= $max_users\nORDER BY id DESC"
    }
   ]
  },
  {
   "title": "Average requests per second (RPS)",
   "type": "timeseries",
   "description": "Make sure to filter out relevant data (correct testplan, user count, etc) or your graph will not be very meaningful. \n\nThe calculation includes internal time taken for Locust to start and stop test, so it will be sligthly lower than the real value, especially for short runs. It also includes the ramp up phase.",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT id AS \"time\", \n rps_avg AS \"avg rps\"\nFROM testrun\nWHERE $__timeFilter(id) and \n testplan = ANY(ARRAY[$testplan]::varchar[]) and -- couldnt use a simple testplan IN ($testplan), because postgres fails if $testplan is empty\n username = ANY(ARRAY[$username]::varchar[]) and\n env = ANY(ARRAY[$env]::varchar[]) and \n num_clients >= $min_users and \n num_clients <= $max_users\nORDER BY id\n"
    },
    {
     "rawSql": "SELECT id AS \"time\", \n rps_avg AS \"avg rps (test failed)\"\nFROM testrun\nWHERE $__timeFilter(id) and \n testplan = ANY(ARRAY[$testplan]::varchar[]) and\n username = ANY(ARRAY[$username]::varchar[]) and\n env = ANY(ARRAY[$env]::varchar[]) and \n num_clients >= $min_users and \n num_clients <= $max_users and exit_code > 0\nORDER BY id\n"
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT id AS \"time\", \n resp_time_avg AS \"avg resp time\"\nFROM testrun\nWHERE $__timeFilter(id) and \n testplan = ANY(ARRAY[$testplan]::varchar[]) and -- couldnt use a simple testplan IN ($testplan), because postgres fails if $testplan is empty\n username = ANY(ARRAY[$username]::varchar[]) and\n env = ANY(ARRAY[$env]::varchar[]) and \n num_clients >= $min_users and \n num_clients <= $max_users\nORDER BY id\n"
    },
    {
     "rawSql": "SELECT id AS \"time\", \n resp_time_avg AS \"avg resp time (failed)\"\nFROM testrun\nWHERE $__timeFilter(id) and \n testplan = ANY(ARRAY[$testplan]::varchar[]) and -- couldnt use a simple testplan IN ($testplan), because postgres fails if $testplan is empty\n username = ANY(ARRAY[$username]::varchar[]) and\n env = ANY(ARRAY[$env]::varchar[]) and \n num_clients >= $min_users and \n num_clients <= $max_users and exit_code > 0\nORDER BY id\n"
    }
   ]
  }
 ]
}